# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Post Image' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Post Image
  pod 'Alamofire'


  target 'Post ImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Post ImageUITests' do
    # Pods for testing
  end

end
